val:
    uv run ty check
    uv run pytest -n4 tests/unit
    uv run pytest tests/integration

dev:
    #!/usr/bin/env bash
    if [[ -z "$FIAB_ROOT" ]] ; then
        if [[ ! -d .fiab ]] ; then mkdir -p .fiab/data_dir ; fi
        echo "1761908420:d0.0.1" > .fiab/pylock.toml.timestamp
    fi
    FIAB_ROOT=.fiab uv run --no-sync python -m forecastbox.entrypoint.main
